[project]
name = "electriccircuitsim"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maciej Krakowiak", email = "maciej.krakowiak17@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pybind11>=2.13.6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
include_package_data = true

[tool.setuptools.package-data]
"src" = ["*.so", "*.pyi"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

