name: Build Package

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build python3-dev

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install . --no-cache-dir

    - name: Build the package
      run: |
        python -m build

    - name: Upload built package
      uses: actions/upload-artifact@v3
      with:
        name: built-wheel
        path: dist/*.whl
