name: Run CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build scikit-build-core pybind11
        python -m build
        pip install dist/*.whl
        pip install pytest pytest-cov pytest-mock


    - name: Run tests
      run: |
        pytest
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.lcov

  c_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake python3 python3-pip python3-dev git pybind11-dev

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake CMakeLists.txt
        sudo make install

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake -B build -DENABLE_TESTING=ON ..
        cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
  build:
    runs-on: ubuntu-latest
    needs: [python_tests, c_tests]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build python3-dev

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build scikit-build-core pybind11

    - name: Build the package
      run: |
        python -m build

    - name: Upload built package
      uses: actions/upload-artifact@v3
      with:
        name: built-wheel
        path: dist/*.whl
